#!/usr/bin/env python3
"""
Generate VHDL ROM packages from MIF files for ModelSim simulation.
Quartus ram_init_file attribute doesn't work in ModelSim;
we embed the data as VHDL constants instead.

Usage: python3 gen_rom_pkg.py
  Reads: wavetable_4wave.mif, fm_log_sine.mif, fm_exp.mif
  Writes: synth_rom_pkg.vhd (in sim/ directory)
"""
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PERIPH_DIR = os.path.dirname(SCRIPT_DIR)


def parse_mif(filepath):
    """Parse Quartus MIF file, return list of (addr, value_int, width)."""
    values = []
    width = 16
    data_radix = 16
    with open(filepath, 'r') as f:
        lines = f.readlines()

    for line in lines:
        line = line.strip()
        if line.startswith('WIDTH'):
            m = re.search(r'WIDTH\s*=\s*(\d+)', line)
            if m:
                width = int(m.group(1))
        elif line.startswith('DEPTH'):
            pass
        elif line.startswith('DATA_RADIX'):
            m = re.search(r'DATA_RADIX\s*=\s*(\w+)', line)
            if m:
                radix_name = m.group(1).upper()
                data_radix = 10 if radix_name == "DEC" else 16
        elif line.startswith('ADDRESS_RADIX'):
            pass
        elif line.upper().startswith('CONTENT') or line.upper().startswith('BEGIN') or line.upper().startswith('END'):
            pass
        elif ':' in line:
            m = re.match(r'([0-9A-Fa-f]+)\s*:\s*([0-9A-Fa-f]+)\s*;', line)
            if m:
                addr = int(m.group(1), 16)
                val = int(m.group(2), data_radix)
                values.append((addr, val, width))
    return values, width


def gen_vhdl_pkg(wavetable, wt_width, log_sine, ls_width, exp_lut, exp_width):
    """Generate VHDL package with all ROM data as constants."""
    lines = []
    lines.append("-- synth_rom_pkg.vhd -- Auto-generated ROM data for simulation")
    lines.append("-- Generated by gen_rom_pkg.py -- DO NOT EDIT")
    lines.append("-- This package provides simulation-compatible ROM initialization")
    lines.append("-- (Quartus ram_init_file attribute doesn't work in ModelSim)")
    lines.append("")
    lines.append("library ieee;")
    lines.append("use ieee.std_logic_1164.all;")
    lines.append("use ieee.numeric_std.all;")
    lines.append("")
    lines.append("package synth_rom_pkg is")
    lines.append("")

    # WAV (signed 16-bit)
    lines.append(f"    -- Wavetable: 1024 x {wt_width}-bit signed (4 waveforms x 256)")
    lines.append(f"    type wavetable_t is array(0 to 1023) of signed({wt_width-1} downto 0);")
    lines.append("    constant WAVETABLE_ROM : wavetable_t := (")
    for i in range(1024):
        addr, val, _ = wavetable[i]
        # Convert unsigned to signed
        if val >= (1 << (wt_width - 1)):
            val_signed = val - (1 << wt_width)
        else:
            val_signed = val
        comma = "," if i < 1023 else ""
        lines.append(f"        {i:4d} => to_signed({val_signed}, {wt_width}){comma}")
    lines.append("    );")
    lines.append("")

    # Log sine (unsigned 12-bit)
    lines.append(f"    -- Log sine LUT: 256 x {ls_width}-bit unsigned")
    lines.append(f"    type log_sine_t is array(0 to 255) of unsigned({ls_width-1} downto 0);")
    lines.append("    constant LOG_SINE_ROM : log_sine_t := (")
    for i in range(256):
        addr, val, _ = log_sine[i]
        comma = "," if i < 255 else ""
        lines.append(f"        {i:3d} => to_unsigned({val}, {ls_width}){comma}")
    lines.append("    );")
    lines.append("")

    # Exp LUT (unsigned 10-bit)
    lines.append(f"    -- Exp LUT: 256 x {exp_width}-bit unsigned")
    lines.append(f"    type exp_lut_t is array(0 to 255) of unsigned({exp_width-1} downto 0);")
    lines.append("    constant EXP_LUT_ROM : exp_lut_t := (")
    for i in range(256):
        addr, val, _ = exp_lut[i]
        comma = "," if i < 255 else ""
        lines.append(f"        {i:3d} => to_unsigned({val}, {exp_width}){comma}")
    lines.append("    );")
    lines.append("")

    lines.append("end package synth_rom_pkg;")
    return "\n".join(lines) + "\n"


def main():
    # Read MIF files
    wavetable, wt_w = parse_mif(os.path.join(PERIPH_DIR, "wavetable_4wave.mif"))
    log_sine, ls_w = parse_mif(os.path.join(PERIPH_DIR, "fm_log_sine.mif"))
    exp_lut, exp_w = parse_mif(os.path.join(PERIPH_DIR, "fm_exp.mif"))

    print(f"Wavetable: {len(wavetable)} entries, {wt_w}-bit")
    print(f"Log sine:  {len(log_sine)} entries, {ls_w}-bit")
    print(f"Exp LUT:   {len(exp_lut)} entries, {exp_w}-bit")

    assert len(wavetable) == 1024, f"Wavetable should be 1024, got {len(wavetable)}"
    assert len(log_sine) == 256, f"Log sine should be 256, got {len(log_sine)}"
    assert len(exp_lut) == 256, f"Exp LUT should be 256, got {len(exp_lut)}"

    # Generate VHDL package
    vhdl = gen_vhdl_pkg(wavetable, wt_w, log_sine, ls_w, exp_lut, exp_w)

    outfile = os.path.join(SCRIPT_DIR, "synth_rom_pkg.vhd")
    with open(outfile, 'w') as f:
        f.write(vhdl)
    print(f"Generated {outfile}")


if __name__ == "__main__":
    main()
