-- neorv32_imem_rom.vhd — Intel/Altera M9K block RAM override for NEORV32 IMEM ROM
--
-- Replaces the upstream neorv32_imem_rom (VHDL constant array) with an altsyncram
-- megafunction configured as ROM, initialized from a MIF file.
--
-- This avoids Quartus OOM caused by synthesizing 64KB of constant data as
-- distributed combinational logic. M9K block RAM uses ~57 blocks out of 432.
--
-- The MIF file (par/neorv32_imem.mif) must be generated by the build pipeline.
library ieee;
use ieee.std_logic_1164.all;

library altera_mf;
use altera_mf.all;

entity neorv32_imem_rom is
  generic (
    AWIDTH : natural; -- address width (byte address)
    OUTREG : natural  -- add output register stage when 1
  );
  port (
    clk_i  : in  std_ulogic;                     -- clock, rising-edge
    en_i   : in  std_ulogic;                     -- access-enable
    addr_i : in  std_ulogic_vector(31 downto 0); -- full byte address
    data_o : out std_ulogic_vector(31 downto 0)  -- read data, sync
  );
end entity neorv32_imem_rom;

architecture rtl of neorv32_imem_rom is

  constant WORDS_C    : natural := 2**(AWIDTH-2);
  constant WORD_ADDR_C : natural := AWIDTH - 2;

  -- altsyncram output (std_logic domain)
  signal q_s : std_logic_vector(31 downto 0);

  -- Output register for OUTREG=1 when altsyncram output is unregistered
  signal rdata_reg : std_ulogic_vector(31 downto 0);

  component altsyncram
  generic (
    address_aclr_a          : string;
    clock_enable_input_a    : string;
    clock_enable_output_a   : string;
    init_file               : string;
    intended_device_family  : string;
    lpm_hint                : string;
    lpm_type                : string;
    numwords_a              : natural;
    operation_mode          : string;
    outdata_aclr_a          : string;
    outdata_regd            : string;
    power_up_uninitialized  : string;
    ram_block_type          : string;
    read_during_write_mode_mixed_ports : string;
    widthad_a               : natural;
    width_a                 : natural
  );
  port (
    clock0    : in  std_logic;
    clocken0  : in  std_logic := '1';
    address_a : in  std_logic_vector(WORD_ADDR_C-1 downto 0);
    q_a       : out std_logic_vector(31 downto 0)
  );
  end component;

begin

  -- altsyncram in ROM mode — always uses internal output register,
  -- matching the original neorv32_imem_rom clocked-process read behavior.
  u_rom : altsyncram
  generic map (
    address_aclr_a          => "NONE",
    clock_enable_input_a    => "NORMAL",
    clock_enable_output_a   => "NORMAL",
    init_file               => "neorv32_imem.mif",
    intended_device_family  => "Cyclone IV E",
    lpm_hint                => "ENABLE_RUNTIME_MOD=NO",
    lpm_type                => "altsyncram",
    numwords_a              => WORDS_C,
    operation_mode          => "ROM",
    outdata_aclr_a          => "NONE",
    outdata_regd            => "REGISTERED",
    power_up_uninitialized  => "FALSE",
    ram_block_type          => "M9K",
    read_during_write_mode_mixed_ports => "DONT_CARE",
    widthad_a               => WORD_ADDR_C,
    width_a                 => 32
  )
  port map (
    clock0    => std_logic(clk_i),
    clocken0  => std_logic(en_i),
    address_a => std_logic_vector(addr_i(AWIDTH-1 downto 2)),
    q_a       => q_s
  );

  -- altsyncram output is always registered (outdata_regd = REGISTERED).
  -- When OUTREG=1 the upstream neorv32_imem adds another register stage.
  -- When OUTREG=0 the data_o is wired directly (the altsyncram register
  -- already provides one pipeline stage, same as the original clocked process).
  outreg_enabled : if OUTREG = 1 generate
    p_outreg : process(clk_i)
    begin
      if rising_edge(clk_i) then
        rdata_reg <= std_ulogic_vector(q_s);
      end if;
    end process;
    data_o <= rdata_reg;
  end generate;

  outreg_disabled : if OUTREG = 0 generate
    data_o <= std_ulogic_vector(q_s);
  end generate;

end architecture rtl;
