#!/usr/bin/env python3
"""Generate wavetable_4wave.mif — 4 waveforms x 256 entries x 16-bit signed.

Address map:
  0x000-0x0FF  Sine
  0x100-0x1FF  Square
  0x200-0x2FF  Sawtooth
  0x300-0x3FF  Triangle

Usage: python3 gen_wavetable.py > wavetable_4wave.mif
"""
import math

N = 256  # entries per waveform

def to_s16(v):
    v = int(round(v))
    v = max(-32768, min(32767, v))
    return v

samples = []

# Sine
for i in range(N):
    samples.append(to_s16(32767 * math.sin(2 * math.pi * i / N)))

# Square
for i in range(N):
    samples.append(0x7FFF if i < N // 2 else 0x8000)

# Sawtooth
for i in range(N):
    samples.append(to_s16(-32768 + 65536 * i / N))

# Triangle
for i in range(N):
    t = i / N
    if t < 0.25:
        samples.append(to_s16(32767 * 4 * t))
    elif t < 0.75:
        samples.append(to_s16(32767 * (2 - 4 * t)))
    else:
        samples.append(to_s16(32767 * (4 * t - 4)))

assert len(samples) == 1024

# Write MIF (Quartus format)
print("-- wavetable_4wave.mif — 1024 x 16-bit signed")
print("-- Generated by gen_wavetable.py")
print(f"WIDTH = 16;")
print(f"DEPTH = 1024;")
print()
print("ADDRESS_RADIX = HEX;")
print("DATA_RADIX = HEX;")
print()
print("CONTENT BEGIN")
for i, s in enumerate(samples):
    # MIF uses 2's complement for negative values
    print(f"    {i:03X} : {s & 0xFFFF:04X};")
print("END;")
