#!/usr/bin/env python3
"""gen_font_rom.py -- Generate CP437 8x16 font ROM for DE2Extra VGA terminal.

Generates from tools/CP437_8x16.bin (4096 bytes, 256 chars x 16 rows):
  1. src/rtl/periph/font_rom_pkg.vhd  (VHDL package)
  2. sw/app/de2shell/gfx_font.h     (C header)

Bit 7 = leftmost pixel, Bit 0 = rightmost pixel.
"""

import os, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
FONT_BIN = os.path.join(SCRIPT_DIR, "CP437_8x16.bin")
VHD_PATH = os.path.join(PROJECT_DIR, "src", "rtl", "periph", "font_rom_pkg.vhd")
C_H_PATH = os.path.join(PROJECT_DIR, "sw", "app", "de2shell", "gfx_font.h")


def format_vhd(data):
    lines = [
        "-- font_rom_pkg.vhd  -- 8x16 CP437 font ROM for VGA text terminal",
        "-- Auto-generated by tools/gen_font_rom.py",
        "-- 256 chars (0x00-0xFF), 16 rows each, 8 bits wide",
        "-- Bit 7 = leftmost pixel, Bit 0 = rightmost pixel",
        "",
        "library IEEE;",
        "use IEEE.STD_LOGIC_1164.ALL;",
        "",
        "package font_rom_pkg is",
        "    type font_rom_t is array (0 to 4095) of std_logic_vector(7 downto 0);",
        "    constant font_rom_data : font_rom_t := (",
    ]

    ctrl_names = {
        0x00: "NUL", 0x01: "SOH", 0x02: "STX", 0x03: "ETX",
        0x04: "EOT", 0x05: "ENQ", 0x06: "ACK", 0x07: "BEL",
        0x08: "BS",  0x09: "HT",  0x0A: "LF",  0x0B: "VT",
        0x0C: "FF",  0x0D: "CR",  0x0E: "SO",  0x0F: "SI",
        0x10: "DLE", 0x11: "DC1", 0x12: "DC2", 0x13: "DC3",
        0x14: "DC4", 0x15: "NAK", 0x16: "SYN", 0x17: "ETB",
        0x18: "CAN", 0x19: "EM",  0x1A: "SUB", 0x1B: "ESC",
        0x1C: "FS",  0x1D: "GS",  0x1E: "RS",  0x1F: "US",
    }
    cp437_names = {
        0x80: "C-cedilla", 0x81: "u-umlaut", 0x82: "e-acute",
        0x83: "a-circumflex", 0x84: "a-umlaut", 0x85: "a-grave",
        0x86: "a-ring", 0x87: "c-cedilla", 0x88: "e-circumflex",
        0x89: "e-umlaut", 0x8A: "e-grave", 0x8B: "i-diaeresis",
        0x8C: "i-circumflex", 0x8D: "i-umlaut", 0x8E: "A-umlaut",
        0x8F: "A-ring", 0x90: "A-ring2", 0x91: "neg", 0x92: "f-ord",
        0x93: "neg2", 0x94: "neg3", 0x95: "neg4", 0x96: "OE",
        0x97: "oe", 0x98: "neg5", 0x99: "neg6",
        0x9A: "SHY", 0x9B: "neg7", 0x9C: "O-slash",
        0x9D: "neg8", 0x9E: "neg9", 0x9F: "Y-acute2",
        0xA0: "NBSP", 0xA1: "i-exclam", 0xA2: "cent",
        0xA3: "sterling", 0xA4: "yen", 0xA5: "yuan",
        0xA6: "broken-bar", 0xA7: "section", 0xA8: "diaeresis",
        0xA9: "copyright", 0xAA: "feminine-ord", 0xAB: "laquo",
        0xAC: "not-sign", 0xAD: "soft-hyphen", 0xAE: "registered",
        0xAF: "macron",
        0xB0: "shade-light", 0xB1: "shade-med", 0xB2: "shade-dark",
        0xB3: "sup3", 0xB4: "box-lr", 0xB5: "micro",
        0xB6: "pilcrow", 0xB7: "middle-dot", 0xB8: "cedilla",
        0xB9: "sup1", 0xBA: "box-vt", 0xBB: "box-rt",
        0xBC: "1/4", 0xBD: "1/2", 0xBE: "3/4", 0xBF: "box-tr",
        0xC0: "box-bl", 0xC1: "box-bt", 0xC2: "box-tp",
        0xC3: "box-lt", 0xC4: "box-hz", 0xC5: "box-x",
        0xC6: "AE", 0xC7: "C-cedilla", 0xC8: "E-grave",
        0xC9: "E-acute", 0xCA: "E-circumflex", 0xCB: "E-diaeresis",
        0xCC: "I-grave", 0xCD: "I-acute", 0xCE: "I-circumflex",
        0xCF: "I-diaeresis",
        0xD0: "ETH", 0xD1: "N-tilde", 0xD2: "O-grave",
        0xD3: "O-acute", 0xD4: "O-circumflex", 0xD5: "O-tilde",
        0xD6: "O-diaeresis", 0xD7: "multiply", 0xD8: "O-slash",
        0xD9: "box-br", 0xDA: "box-tl", 0xDB: "full-block",
        0xDC: "U-diaeresis", 0xDD: "Y-acute", 0xDE: "THORN",
        0xDF: "sharp-s",
        0xE0: "a-grave", 0xE1: "a-acute", 0xE2: "a-circumflex",
        0xE3: "a-tilde", 0xE4: "a-diaeresis", 0xE5: "a-ring",
        0xE6: "ae", 0xE7: "c-cedilla", 0xE8: "e-grave",
        0xE9: "e-acute", 0xEA: "e-circumflex", 0xEB: "e-diaeresis",
        0xEC: "i-grave", 0xED: "i-acute", 0xEE: "i-circumflex",
        0xEF: "i-diaeresis",
        0xF0: "eth", 0xF1: "n-tilde", 0xF2: "o-grave",
        0xF3: "o-acute", 0xF4: "o-circumflex", 0xF5: "o-tilde",
        0xF6: "o-diaeresis", 0xF7: "divide", 0xF8: "o-slash",
        0xF9: "u-grave", 0xFA: "u-acute", 0xFB: "u-circumflex",
        0xFC: "u-diaeresis", 0xFD: "y-acute", 0xFE: "thorn",
        0xFF: "y-diaeresis",
    }

    for ch in range(256):
        if ch < 0x20:
            label = f"  -- 0x{ch:02X} {ctrl_names.get(ch, f'CTRL{ch:02X}')}"
        elif ch == 0x20:
            label = "  -- 0x20 SP"
        elif ch < 0x7F:
            label = f"  -- 0x{ch:02X} {chr(ch)}"
        elif ch == 0x7F:
            label = "  -- 0x7F DEL"
        else:
            label = f"  -- 0x{ch:02X} {cp437_names.get(ch, 'UNKN')}"
        lines.append(label)

        for row in range(16):
            b = data[ch * 16 + row]
            suffix = "," if (ch != 255 or row != 15) else ""
            lines.append(f'        x"{b:02X}"{suffix}  -- row {row}')

    lines.append("    );")
    lines.append("end package font_rom_pkg;")
    return "\n".join(lines) + "\n"


def format_c_header(data):
    lines = [
        "/* gfx_font.h -- CP437 8x16 bitmap font data",
        " *",
        " * Full 256 chars (0x00-0xFF) of Code Page 437.",
        " * Bit 7 = leftmost pixel, Bit 0 = rightmost pixel.",
        " * Auto-generated by tools/gen_font_rom.py",
        " */",
        "#ifndef GFX_FONT_H",
        "#define GFX_FONT_H",
        "",
        "#include <stdint.h>",
        "",
        "#define FONT_W 8",
        "#define FONT_H 16",
        "#define FONT_CHARS 256",
        "",
        "static const uint8_t font_8x16[FONT_CHARS][FONT_H] = {",
    ]

    for ch in range(256):
        row_bytes = ", ".join(f"0x{data[ch * 16 + row]:02X}" for row in range(16))
        lines.append(f"    /* 0x{ch:02X} */ {{{row_bytes}}},")

    lines.append("};")
    lines.append("")
    lines.append("#endif /* GFX_FONT_H */")
    return "\n".join(lines) + "\n"


def main():
    if not os.path.exists(FONT_BIN):
        print(f"ERROR: {FONT_BIN} not found (need 4096 bytes)")
        print("Generate it with: python3 tools/extract_cp437.py")
        sys.exit(1)

    with open(FONT_BIN, "rb") as f:
        data = f.read()

    if len(data) != 4096:
        print(f"ERROR: {FONT_BIN} has {len(data)} bytes, expected 4096")
        sys.exit(1)

    print(f"Loaded {FONT_BIN} ({len(data)} bytes)")

    vhd = format_vhd(data)
    c_h = format_c_header(data)

    with open(VHD_PATH, "w") as f:
        f.write(vhd)
    print(f"  Wrote {VHD_PATH} ({len(vhd)} bytes)")

    with open(C_H_PATH, "w") as f:
        f.write(c_h)
    print(f"  Wrote {C_H_PATH} ({len(c_h)} bytes)")


if __name__ == "__main__":
    main()
