/* system_fth.h -- pForth system.fth for runtime interpretation */
#ifndef SYSTEM_FTH_H
#define SYSTEM_FTH_H

static const char g_system_fth[] =
": FIRST_COLON ;\n"
"\n"
": LATEST context @ ;\n"
"\n"
": FLAG_IMMEDIATE 64 ;\n"
"\n"
": IMMEDIATE\n"
"        latest dup c@ flag_immediate OR\n"
"        swap c!\n"
";\n"
"\n"
": (   41 word drop ; immediate\n"
"( That was the definition for the comment word. )\n"
"( Now we can add comments to what we are doing! )\n"
"( Note that we are in decimal numeric input mode. )\n"
"\n"
": \\ ( <line> -- , comment out rest of line )\n"
"        EOL word drop\n"
"; immediate\n"
"\n"
"\\ 1 echo !  \\ Uncomment this line to echo Forth code while compiling.\n"
"\n"
"\\ *********************************************************************\n"
"\\ This is another style of comment that is common in Forth.\n"
"\\ pFORTH - Portable Forth System\n"
"\\ Based on HMSL Forth\n"
"\\\n"
"\\ Author: Phil Burk\n"
"\\ Copyright 1994 3DO, Phil Burk, Larry Polansky, David Rosenboom\n"
"\\\n"
"\\ Permission to use, copy, modify, and/or distribute this\n"
"\\ software for any purpose with or without fee is hereby granted.\n"
"\\\n"
"\\ THE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL\n"
"\\ WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED\n"
"\\ WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL\n"
"\\ THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR\n"
"\\ CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING\n"
"\\ FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF\n"
"\\ CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF\n"
"\\ OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.\n"
"\\ *********************************************************************\n"
"\n"
": COUNT  dup 1+ swap c@ ;\n"
"\n"
"\\ Miscellaneous support words\n"
": ON ( addr -- , set true )\n"
"        -1 swap !\n"
";\n"
": OFF ( addr -- , set false )\n"
"        0 swap !\n"
";\n"
"\n"
": CELL+ ( n -- n+cell )  cell + ;\n"
": CELL- ( n -- n+cell )  cell - ;\n"
": CELL* ( n -- n*cell )  cells ;\n"
"\n"
": CHAR+ ( n -- n+size_of_char ) 1+ ;\n"
": CHARS ( n -- n*size_of_char , don't do anything)  ; immediate\n"
"\n"
"\\ useful stack manipulation words\n"
": -ROT ( a b c -- c a b )\n"
"        rot rot\n"
";\n"
": 3DUP ( a b c -- a b c a b c )\n"
"        2 pick 2 pick 2 pick\n"
";\n"
": 2DROP ( a b -- )\n"
"        drop drop\n"
";\n"
": NIP ( a b -- b )\n"
"        swap drop\n"
";\n"
": TUCK ( a b -- b a b )\n"
"        swap over\n"
";\n"
"\n"
": <= ( a b -- f , true if A <= b )\n"
"        > 0=\n"
";\n"
": >= ( a b -- f , true if A >= b )\n"
"        < 0=\n"
";\n"
"\n"
": INVERT ( n -- 1'comp )\n"
"    -1 xor\n"
";\n"
"\n"
": NOT ( n -- !n , logical negation )\n"
"        0=\n"
";\n"
"\n"
": NEGATE ( n -- -n )\n"
"        0 swap -\n"
";\n"
"\n"
": DNEGATE ( d -- -d , negate by doing 0-d )\n"
"        0 0 2swap d-\n"
";\n"
"\n"
"\n"
"\\ --------------------------------------------------------------------\n"
"\n"
": ID.   ( nfa -- )\n"
"    count mask_name_size and type\n"
";\n"
"\n"
": DECIMAL   10 base !  ;\n"
": OCTAL      8 base !  ;\n"
": HEX       16 base !  ;\n"
": BINARY     2 base !  ;\n"
"\n"
": PAD ( -- addr )\n"
"        here 128 +\n"
";\n"
"\n"
": $MOVE ( $src $dst -- )\n"
"        over c@ 1+ cmove\n"
";\n"
": BETWEEN ( n lo hi -- flag , true if between lo & hi )\n"
"        >r over r> > >r\n"
"        < r> or 0=\n"
";\n"
": [ ( -- , enter interpreter mode )\n"
"        0 state !\n"
"; immediate\n"
": ] ( -- enter compile mode )\n"
"        1 state !\n"
";\n"
"\n"
": EVEN-UP  ( n -- n | n+1 , make even )  dup 1 and +  ;\n"
": ALIGNED  ( addr -- a-addr )\n"
"        [ cell 1- ] literal +\n"
"        [ cell 1- invert ] literal and\n"
";\n"
": ALIGN ( -- , align DP )  dp @ aligned dp ! ;\n"
": ALLOT ( nbytes -- , allot space in dictionary ) dp +! ( align ) ;\n"
"\n"
": C,    ( c -- )  here c! 1 chars dp +! ;\n"
": W,    ( w -- )  dp @ even-up dup dp !    w!  2 chars dp +! ;\n"
": , ( n -- , lay into dictionary )  align here !  cell allot ;\n"
"\n"
"\\ Dictionary conversions ------------------------------------------\n"
"\n"
": N>NEXTLINK  ( nfa -- nextlink , traverses name field )\n"
"        dup c@ mask_name_size and 1+ + aligned\n"
";\n"
"\n"
": NAMEBASE  ( -- base-of-names )\n"
"        Headers-Base @\n"
";\n"
": CODEBASE  ( -- base-of-code dictionary )\n"
"        Code-Base @\n"
";\n"
"\n"
": NAMELIMIT  ( -- limit-of-names )\n"
"        Headers-limit @\n"
";\n"
": CODELIMIT  ( -- limit-of-code, last address in dictionary )\n"
"        Code-limit @\n"
";\n"
"\n"
": NAMEBASE+   ( rnfa -- nfa , convert relocatable nfa to actual )\n"
"        namebase +\n"
";\n"
"\n"
": >CODE ( xt -- secondary_code_address, not valid for primitives )\n"
"        codebase +\n"
";\n"
"\n"
": CODE> ( secondary_code_address -- xt , not valid for primitives )\n"
"        codebase -\n"
";\n"
"\n"
": N>LINK  ( nfa -- lfa )\n"
"        2 CELLS -\n"
";\n"
"\n"
": >BODY   ( xt -- pfa )\n"
"    >code body_offset +\n"
";\n"
"\n"
": BODY>   ( pfa -- xt )\n"
"    body_offset - code>\n"
";\n"
"\n"
"\\ convert between addresses usable by @, and relocatable addresses.\n"
": USE->REL  ( useable_addr -- rel_addr )\n"
"        codebase -\n"
";\n"
": REL->USE  ( rel_addr -- useable_addr )\n"
"        codebase +\n"
";\n"
"\n"
"\\ for JForth code\n"
"\\ : >REL  ( adr -- adr )  ; immediate\n"
"\\ : >ABS  ( adr -- adr )  ; immediate\n"
"\n"
": X@ ( addr -- xt , fetch execution token from relocatable )   @ ;\n"
": X! ( addr -- xt , store execution token as relocatable )   ! ;\n"
"\n"
"\\ Compiler support ------------------------------------------------\n"
": COMPILE, ( xt -- , compile call to xt )\n"
"        ,\n"
";\n"
"\n"
"( Compiler support , based on FIG )\n"
": [COMPILE]  ( <name> -- , compile now even if immediate )\n"
"    ' compile,\n"
";  IMMEDIATE\n"
"\n"
": (COMPILE) ( xt -- , postpone compilation of token )\n"
"        [compile] literal       ( compile a call to literal )\n"
"        ( store xt of word to be compiled )\n"
"\n"
"        [ ' compile, ] literal   \\ compile call to compile,\n"
"        compile,\n"
";\n"
"\n"
": COMPILE  ( <name> -- , save xt and compile later )\n"
"    ' (compile)\n"
"; IMMEDIATE\n"
"\n"
"\n"
": :NONAME ( -- xt , begin compilation of headerless secondary )\n"
"        align\n"
"        here code>   \\ convert here to execution token\n"
"        ]\n"
";\n"
"\n"
"\\ Error codes defined in ANSI Exception word set.\n"
": ERR_ABORT         -1 ;   \\ general abort\n"
": ERR_ABORTQ        -2 ;   \\ for abort\"\n"
": ERR_EXECUTING    -14 ;   \\ compile time word while not compiling\n"
": ERR_PAIRS        -22 ;   \\ mismatch in conditional\n"
": ERR_DEFER       -258 ;  \\ not a deferred word\n"
"\n"
": ABORT ( i*x -- )\n"
"    ERR_ABORT throw\n"
";\n"
"\n"
"\\ Conditionals in '83 form -----------------------------------------\n"
": CONDITIONAL_KEY ( -- , lazy constant ) 29521 ;\n"
": ?CONDITION   ( f -- )  conditional_key - err_pairs ?error ;\n"
": >MARK      ( -- addr )   here 0 ,  ;\n"
": >RESOLVE   ( addr -- )   here over - swap !  ;\n"
": <MARK      ( -- addr )   here  ;\n"
": <RESOLVE   ( addr -- )   here - ,  ;\n"
"\n"
": ?COMP  ( -- , error if not compiling )\n"
"        state @ 0= err_executing ?error\n"
";\n"
": ?PAIRS ( n m -- )\n"
"        - err_pairs ?error\n"
";\n"
"\\ conditional primitives\n"
": IF     ( -- f orig )  ?comp compile 0branch  conditional_key >mark     ; immediate\n"
": THEN   ( f orig -- )  swap ?condition  >resolve   ; immediate\n"
": BEGIN  ( -- f dest )  ?comp conditional_key <mark   ; immediate\n"
": AGAIN  ( f dest -- )  compile branch  swap ?condition  <resolve  ; immediate\n"
": UNTIL  ( f dest -- )  compile 0branch swap ?condition  <resolve  ; immediate\n"
": AHEAD  ( -- f orig )  compile branch   conditional_key >mark     ; immediate\n"
"\n"
"\\ conditionals built from primitives\n"
": ELSE   ( f orig1 -- f orig2 )\n"
"    [compile] AHEAD  2swap [compile] THEN  ; immediate\n"
": WHILE  ( f dest -- f orig f dest )  [compile]  if   2swap ; immediate\n"
": REPEAT ( -- f orig f dest ) [compile] again  [compile] then  ; immediate\n"
"\n"
": [']  ( <name> -- xt , define compile time tick )\n"
"        ?comp ' [compile] literal\n"
"; immediate\n"
"\n"
"\\ for example:\n"
"\\ compile time:  compile create , (does>) then ;\n"
"\\ execution time:  create <name>, ',' data, then patch pi to point to @\n"
"\\    : con create , does> @ ;\n"
"\\    345 con pi\n"
"\\    pi\n"
"\\\n"
": (DOES>)  ( xt -- , modify previous definition to execute code at xt )\n"
"        latest name> >code \\ get address of code for new word\n"
"        cell + \\ offset to second cell in create word\n"
"        !      \\ store execution token of DOES> code in new word\n"
";\n"
"\n"
": DOES>   ( -- , define execution code for CREATE word )\n"
"        0 [compile] literal \\ dummy literal to hold xt\n"
"        here cell-          \\ address of zero in literal\n"
"        compile (does>)     \\ call (DOES>) from new creation word\n"
"        >r                  \\ move addrz to return stack so ; doesn't see stack garbage\n"
"        [compile] ;         \\ terminate part of code before does>\n"
"        r>\n"
"        :noname       ( addrz xt )\n"
"        swap !              \\ save execution token in literal\n"
"; immediate\n"
"\n"
": VARIABLE  ( <name> -- )\n"
"    CREATE 0 , \\ IMMEDIATE\n"
"\\       DOES> [compile] aliteral  \\ %Q This could be optimised\n"
";\n"
"\n"
": 2VARIABLE  ( <name> -c- ) ( -x- addr )\n"
"        create 0 , 0 ,\n"
";\n"
"\n"
": CONSTANT  ( n <name> -c- ) ( -x- n )\n"
"        CREATE , ( n -- )\n"
"        DOES> @ ( -- n )\n"
";\n"
"\n"
"\n"
"\n"
"0 1- constant -1\n"
"0 2- constant -2\n"
"\n"
": 2! ( x1 x2 addr -- , store x2 followed by x1 )\n"
"        swap over ! cell+ !\n"
";\n"
": 2@ ( addr -- x1 x2 )\n"
"        dup cell+ @ swap @\n"
";\n"
"\n"
": 2CONSTANT ( n1 n2 <name> -c- ) ( -x- n1 n2 )\n"
"        CREATE , , ( n1 n2 -- )\n"
"        DOES> 2@   ( -- n1 n2 )\n"
";\n"
"\n"
": ABS ( n -- |n| )\n"
"        dup 0<\n"
"        IF negate\n"
"        THEN\n"
";\n"
": DABS ( d -- |d| )\n"
"        dup 0<\n"
"        IF dnegate\n"
"        THEN\n"
";\n"
"\n"
": S>D  ( s -- d , extend signed single precision to double )\n"
"        dup 0<\n"
"        IF -1\n"
"        ELSE 0\n"
"        THEN\n"
";\n"
"\n"
": D>S ( d -- s ) drop ;\n"
"\n"
": /MOD ( a b -- rem quo , unsigned version, FIXME )\n"
"        >r s>d r> um/mod\n"
";\n"
"\n"
": MOD ( a b -- rem )\n"
"        /mod drop\n"
";\n"
"\n"
": 2* ( n -- n*2 )\n"
"        1 lshift\n"
";\n"
": 2/ ( n -- n/2 )\n"
"        1 arshift\n"
";\n"
"\n"
": D2*  ( d -- d*2 )\n"
"        2* over\n"
"        cell 8 * 1- rshift or  swap\n"
"        2* swap\n"
";\n"
"\n"
": D= ( xd1 xd2 -- flag )\n"
"	rot = -rot = and\n"
";\n"
"\n"
": D< ( d1 d2 -- flag )\n"
"    d- nip 0<\n"
";\n"
"\n"
": D> ( d1 d2 -- flag )\n"
"    2swap d<\n"
";\n"
"\n"
"\\ define some useful constants ------------------------------\n"
"1 0= constant FALSE\n"
"0 0= constant TRUE\n"
"32 constant BL\n"
"\n"
"\n"
"\\ Store and Fetch relocatable data addresses. ---------------\n"
": IF.USE->REL  ( use -- rel , preserve zero )\n"
"        dup IF use->rel THEN\n"
";\n"
": IF.REL->USE  ( rel -- use , preserve zero )\n"
"        dup IF rel->use THEN\n"
";\n"
"\n"
": A!  ( dictionary_address addr -- )\n"
"    >r if.use->rel r> !\n"
";\n"
": A@  ( addr -- dictionary_address )\n"
"    @ if.rel->use\n"
";\n"
"\n"
": A, ( dictionary_address -- )\n"
"    if.use->rel ,\n"
";\n"
"\n"
"\\ Stack data structure ----------------------------------------\n"
"\\ This is a general purpose stack utility used to implement necessary\n"
"\\ stacks for the compiler or the user.  Not real fast.\n"
"\\ These stacks grow up which is different then normal.\n"
"\\   cell 0 - stack pointer, offset from pfa of word\n"
"\\   cell 1 - limit for range checking\n"
"\\   cell 2 - first data location\n"
"\n"
": :STACK   ( #cells -- )\n"
"        CREATE  2 cells ,          ( offset of first data location )\n"
"                dup ,              ( limit for range checking, not currently used )\n"
"                cells cell+ allot  ( allot an extra cell for safety )\n"
";\n"
"\n"
": >STACK  ( n stack -- , push onto stack, postincrement )\n"
"        dup @ 2dup cell+ swap ! ( -- n stack offset )\n"
"        + !\n"
";\n"
"\n"
": STACK>  ( stack -- n , pop , predecrement )\n"
"        dup @ cell- 2dup swap !\n"
"        + @\n"
";\n"
"\n"
": STACK@ ( stack -- n , copy )\n"
"        dup @ cell- + @\n"
";\n"
"\n"
": STACK.PICK ( index stack -- n , grab Nth from top of stack )\n"
"        dup @ cell- +\n"
"        swap cells -   \\ offset for index\n"
"        @\n"
";\n"
": STACKP ( stack -- ptr , to next empty location on stack )\n"
"    dup @ +\n"
";\n"
"\n"
": 0STACKP  ( stack -- , clear stack)\n"
"    8 swap !\n"
";\n"
"\n"
"32 :stack ustack\n"
"ustack 0stackp\n"
"\n"
"\\ Define JForth like words.\n"
": >US ustack >stack ;\n"
": US> ustack stack> ;\n"
": US@ ustack stack@ ;\n"
": 0USP ustack 0stackp ;\n"
"\n"
"\n"
"\\ DO LOOP ------------------------------------------------\n"
"\n"
"3 constant do_flag\n"
"4 constant leave_flag\n"
"5 constant ?do_flag\n"
"\n"
": DO    ( -- , loop-back do_flag jump-from ?do_flag )\n"
"        ?comp\n"
"        compile  (do)\n"
"        here >us do_flag  >us  ( for backward branch )\n"
"; immediate\n"
"\n"
": ?DO    ( -- , loop-back do_flag jump-from ?do_flag  , on user stack )\n"
"        ?comp\n"
"        ( leave address to set for forward branch )\n"
"        compile  (?do)\n"
"        here 0 ,\n"
"        here >us do_flag  >us  ( for backward branch )\n"
"        >us ( for forward branch ) ?do_flag >us\n"
"; immediate\n"
"\n"
": LEAVE  ( -- addr leave_flag )\n"
"        compile (leave)\n"
"        here 0 , >us\n"
"        leave_flag >us\n"
"; immediate\n"
"\n"
": LOOP-FORWARD  ( -us- jump-from ?do_flag -- )\n"
"        BEGIN\n"
"                us@ leave_flag =\n"
"                us@ ?do_flag =\n"
"                OR\n"
"        WHILE\n"
"                us> leave_flag =\n"
"                IF\n"
"                        us> here over - cell+ swap !\n"
"                ELSE\n"
"                        us> dup\n"
"                        here swap -\n"
"                        cell+ swap !\n"
"                THEN\n"
"        REPEAT\n"
";\n"
"\n"
": LOOP-BACK  (  loop-addr do_flag -us- )\n"
"        us> do_flag ?pairs\n"
"        us> here -  here\n"
"        !\n"
"        cell allot\n"
";\n"
"\n"
": LOOP    ( -- , loop-back do_flag jump-from ?do_flag )\n"
"   compile  (loop)\n"
"   loop-forward loop-back\n"
"; immediate\n"
"\n"
"\\ : DOTEST 5 0 do 333 . loop 888 . ;\n"
"\\ : ?DOTEST0 0 0 ?do 333 . loop 888 . ;\n"
"\\ : ?DOTEST1 5 0 ?do 333 . loop 888 . ;\n"
"\n"
": +LOOP    ( -- , loop-back do_flag jump-from ?do_flag )\n"
"   compile  (+loop)\n"
"   loop-forward loop-back\n"
"; immediate\n"
"\n"
": UNLOOP ( loop-sys -r- )\n"
"        r> \\ save return pointer\n"
"        rdrop rdrop\n"
"        >r\n"
";\n"
"\n"
": RECURSE ( ? -- ? , call the word currently being defined )\n"
"        latest  name> compile,\n"
"; immediate\n"
"\n"
"\n"
"\n"
": SPACE  bl emit ;\n"
": SPACES  512 min 0 max 0 ?DO space LOOP ;\n"
": 0SP depth 0 ?do drop loop ;\n"
"\n"
": >NEWLINE ( -- , CR if needed )\n"
"        out @ 0>\n"
"        IF cr\n"
"        THEN\n"
";\n"
"\n"
"\n"
"\\ Support for DEFER --------------------\n"
": CHECK.DEFER  ( xt -- , error if not a deferred word by comparing to type )\n"
"    >code @\n"
"        ['] emit >code @\n"
"        - err_defer ?error\n"
";\n"
"\n"
": >is ( xt -- address_of_vector )\n"
"        >code\n"
"        cell +\n"
";\n"
"\n"
": (IS)  ( xt_do xt_deferred -- )\n"
"        >is !\n"
";\n"
"\n"
": IS  ( xt <name> -- , act like normal IS )\n"
"        '  \\ xt\n"
"        dup check.defer\n"
"        state @\n"
"        IF [compile] literal compile (is)\n"
"        ELSE (is)\n"
"        THEN\n"
"; immediate\n"
"\n"
": (WHAT'S)  ( xt -- xt_do )\n"
"        >is @\n"
";\n"
": WHAT'S  ( <name> -- xt , what will deferred word call? )\n"
"        '  \\ xt\n"
"        dup check.defer\n"
"        state @\n"
"        IF [compile] literal compile (what's)\n"
"        ELSE (what's)\n"
"        THEN\n"
"; immediate\n"
"\n"
": /STRING   ( addr len n -- addr' len' )\n"
"   over min  rot over   +  -rot  -\n"
";\n"
": PLACE   ( addr len to -- , move string )\n"
"   3dup  1+  swap cmove  c! drop\n"
";\n"
"\n"
": PARSE-WORD   ( char -- addr len )\n"
"   >r  source tuck >in @ /string  r@ skip over swap r> scan\n"
"   >r  over -  rot r>  dup 0<> + - >in !\n"
";\n"
": PARSE   ( char -- addr len )\n"
"   >r  source >in @  /string  over swap  r> scan\n"
"   >r  over -  dup r> 0<>  -  >in +!\n"
";\n"
"\n"
": LWORD  ( char -- addr )\n"
"        parse-word here place here \\ 00002 , use PARSE-WORD\n"
";\n"
"\n"
": ASCII ( <char> -- char , state smart )\n"
"        bl parse drop c@\n"
"        state @\n"
"        IF [compile] literal\n"
"        THEN\n"
"; immediate\n"
"\n"
": CHAR ( <char> -- char , interpret mode )\n"
"        bl parse drop c@\n"
";\n"
"\n"
": [CHAR] ( <char> -- char , for compile mode )\n"
"        char [compile] literal\n"
"; immediate\n"
"\n"
": $TYPE  ( $string -- )\n"
"        count type\n"
";\n"
"\n"
": 'word   ( -- addr )   here ;\n"
"\n"
": EVEN    ( addr -- addr' )   dup 1 and +  ;\n"
"\n"
": (C\")   ( -- $addr , some Forths return addr AND count, OBSOLETE?)\n"
"        r> dup count + aligned >r\n"
";\n"
": (S\")   ( -- c-addr cnt )\n"
"        r> count 2dup + aligned >r\n"
";\n"
"\n"
": (.\")  ( -- , type following string )\n"
"        r> count 2dup + aligned >r type\n"
";\n"
"\n"
": \",  ( adr len -- , place string into dictionary )\n"
"         tuck 'word place 1+ allot align\n"
";\n"
": ,\"   ( -- )\n"
"   [char] \" parse \",\n"
";\n"
"\n"
": .(  ( <string> -- , type string delimited by parentheses )\n"
"    [CHAR] ) PARSE TYPE\n"
"; IMMEDIATE\n"
"\n"
": .\"   ( <string> -- , type string )\n"
"        state @\n"
"        IF      compile (.\")  ,\"\n"
"        ELSE [char] \" parse type\n"
"        THEN\n"
"; immediate\n"
"\n"
"\n"
": .'   ( <string> -- , type string delimited by single quote )\n"
"        state @\n"
"        IF    compile (.\")  [char] ' parse \",\n"
"        ELSE [char] ' parse type\n"
"        THEN\n"
"; immediate\n"
"\n"
": C\"    ( <string> -- addr , return string address, ANSI )\n"
"        state @\n"
"        IF compile (c\")   ,\"\n"
"        ELSE [char] \" parse pad place pad\n"
"        THEN\n"
"; immediate\n"
"\n"
": S\"    ( <string> -- , -- addr , return string address, ANSI )\n"
"        state @\n"
"        IF compile (s\")   ,\"\n"
"        ELSE [char] \" parse pad place pad count\n"
"        THEN\n"
"; immediate\n"
"\n"
": \"    ( <string> -- , -- addr , return string address )\n"
"        [compile] C\"\n"
"; immediate\n"
": P\"    ( <string> -- , -- addr , return string address )\n"
"        [compile] C\"\n"
"; immediate\n"
"\n"
": \"\"  ( <string> -- addr )\n"
"        state @\n"
"        IF\n"
"                compile (C\")\n"
"                bl parse-word  \",\n"
"        ELSE\n"
"                bl parse-word pad place pad\n"
"        THEN\n"
"; immediate\n"
"\n"
": SLITERAL ( addr cnt -- , compile string )\n"
"    compile (S\")\n"
"    \",\n"
"; IMMEDIATE\n"
"\n"
": $APPEND ( addr count $1 -- , append text to $1 )\n"
"    over >r\n"
"        dup >r\n"
"    count +  ( -- a2 c2 end1 )\n"
"    swap cmove\n"
"    r> dup c@  ( a1 c1 )\n"
"    r> + ( -- a1 totalcount )\n"
"    swap c!\n"
";\n"
"\n"
"\n"
"\\ ANSI word to replace [COMPILE] and COMPILE ----------------\n"
": POSTPONE  ( <name> -- )\n"
"    bl word find\n"
"    dup 0=\n"
"    IF\n"
"        .\" Postpone could not find \" count type cr abort\n"
"    ELSE\n"
"        0>\n"
"        IF compile,  \\ immediate\n"
"        ELSE (compile)  \\ normal\n"
"        THEN\n"
"    THEN\n"
"; immediate\n"
"\n"
"\\ -----------------------------------------------------------------\n"
"\\ Auto Initialization\n"
": AUTO.INIT  ( -- )\n"
"\\ Kernel finds AUTO.INIT and executes it after loading dictionary.\n"
"\\   .\" Begin AUTO.INIT ------\" cr\n"
";\n"
": AUTO.TERM  ( -- )\n"
"\\ Kernel finds AUTO.TERM and executes it on bye.\n"
"\\   .\" End AUTO.TERM ------\" cr\n"
";\n"
"\n"
"\\ -------------- INCLUDE ------------------------------------------\n"
"variable TRACE-INCLUDE\n"
"\n"
": INCLUDE.MARK.START  ( c-addr u -- , mark start of include for FILE?)\n"
"    dup 5 + allocate throw >r\n"
"    \" ::::\" r@ $move\n"
"    r@ $append\n"
"    r@ ['] noop (:)\n"
"    r> free throw\n"
";\n"
"\n"
": INCLUDE.MARK.END  ( -- , mark end of include )\n"
"    \" ;;;;\" ['] noop (:)\n"
";\n"
"\n"
": INCLUDED ( c-addr u -- )\n"
"	\\ Print messages.\n"
"        trace-include @\n"
"        IF\n"
"                >newline .\" Include \" 2dup type cr\n"
"        THEN\n"
"        here >r\n"
"        2dup r/o open-file\n"
"        IF  ( -- c-addr u bad-fid )\n"
"                drop .\" Could not find file \" type cr abort\n"
"        ELSE ( -- c-addr u good-fid )\n"
"		-rot include.mark.start\n"
"                depth >r\n"
"                include-file    \\ will also close the file\n"
"                depth 1+ r> -\n"
"                IF\n"
"                        .\" Warning: stack depth changed during include!\" cr\n"
"                        .s cr\n"
"                        0sp\n"
"                THEN\n"
"                include.mark.end\n"
"        THEN\n"
"        trace-include @\n"
"        IF\n"
"                .\"     include added \" here r@ - . .\" bytes,\"\n"
"                codelimit here - . .\" left.\" cr\n"
"        THEN\n"
"        rdrop\n"
";\n"
"\n"
"defer MAP.FILENAME ( $filename1 -- $filename2 , modify name )\n"
"' noop is map.filename\n"
"\n"
": $INCLUDE ( $filename -- )\n"
"    map.filename\n"
"    count included\n"
";\n"
"\n"
"create INCLUDE-SAVE-NAME 128 allot\n"
": INCLUDE ( <fname> -- )\n"
"        BL lword\n"
"        dup include-save-name $move  \\ save for RI\n"
"        $include\n"
";\n"
"\n"
": RI ( -- , ReInclude previous file as a convenience )\n"
"        include-save-name $include\n"
";\n"
"\n"
": INCLUDE? ( <word> <file> -- , load file if word not defined )\n"
"        bl word find\n"
"        IF drop bl word drop  ( eat word from source )\n"
"        ELSE drop include\n"
"        THEN\n"
";\n"
"\n"
"\\ desired sizes for dictionary loaded after SAVE-FORTH\n"
"variable HEADERS-SIZE\n"
"variable CODE-SIZE\n"
"\n"
": AUTO.INIT\n"
"    auto.init\n"
"    codelimit codebase - code-size !\n"
"    namelimit namebase - headers-size !\n"
";\n"
"auto.init\n"
"\n"
": SAVE-FORTH ( $name -- )\n"
"    0                                    \\ Entry point\n"
"    headers-ptr @ namebase - 65536 +     \\ NameSize\n"
"    headers-size @ MAX\n"
"    here codebase - 131072 +              \\ CodeSize\n"
"    code-size @ MAX\n"
"    (save-forth)\n"
"    IF\n"
"        .\" SAVE-FORTH failed!\" cr abort\n"
"    THEN\n"
";\n"
"\n"
": TURNKEY ( $name entry-token-- )\n"
"    0     \\ NameSize = 0, names not saved in turnkey dictionary\n"
"    here codebase - 131072 +             \\ CodeSize, remember that base is HEX\n"
"    (save-forth)\n"
"    IF\n"
"        .\" TURNKEY failed!\" cr abort\n"
"    THEN\n"
";\n"
"\n"
"\\ Now that we can load from files, load remainder of dictionary.\n"
"\n"
"trace-include on\n"
"\\ Turn this OFF if you do not want to see the contents of the stack after each entry.\n"
"trace-stack off\n"
"\n"
"\n"
"decimal\n"
"\n"
": ;;;; ;  \\ Mark end of this file so FILE? can find things in here.\n"
"    \\ prevent forgetting below this point\n"
"\n"
".( Dictionary compiled, save in \"pforth.dic\".) cr\n"
"\\ 300000 headers-size !\n"
"\\ 700000 code-size !\n"
"\n"
;

#endif /* SYSTEM_FTH_H */
